name: Coding Style
description: Check coding style

runs:
  using: composite
  steps:

    - name: CS check (Composer Defined)
      shell: bash
      run: composer cs-fix -- --dry-run --format=checkstyle | cs2pr

    - name: Echo banner
      shell: bash
      run: echo "Coding style check successful" >> $GITHUB_STEP_SUMMARY
