name: Setup Environment
description: Setup environment for testing

inputs:
  environment:
    description: 'Environment(s) to setup, besides php, e.g. mysql, etc.'
    required: true
  php-version:
    description: 'PHP version to use'
    required: true
  php-extensions:
    description: 'PHP extensions to install'
    required: false
    default: swoole, posix, json
  operating-system:
    description: 'Operating system to use'
    required: true
  use-cache:
    description: 'Use cache for composer'
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Echo banner
      shell: bash
      run: |
        echo "## Environment Info" >> $GITHUB_STEP_SUMMARY
        echo "#### Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "================" >> $GITHUB_STEP_SUMMARY
        echo "#### OS: ${{ inputs.operating-system }}" >> $GITHUB_STEP_SUMMARY
        echo "#### PHP: ${{ inputs.php-version }}" >> $GITHUB_STEP_SUMMARY
        echo "#### Extensions: ${{ inputs.php-extensions }}" >> $GITHUB_STEP_SUMMARY
        echo "#### Environment: ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "#### Cache: ${{ inputs.use-cache }}" >> $GITHUB_STEP_SUMMARY
        echo "================" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        tools: cs2pr

    - name: Setup problem matchers for PHP
      shell: bash
      run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

    - name: Validate composer.json and composer.lock
      shell: bash
      run: composer validate --strict

    - name: Get composer cache directory
      shell: bash
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache composer dependencies
      if: inputs.use-cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install composer dependencies
      shell: bash
      run: composer install --prefer-dist --no-progress

    # TODO: Setup other environments, e.g. mysql, redis, etc.
